export const ERROR_MISSING_CHROMOSOMES = 'ERROR_MISSING_CHROMOSOMES';
export const ERROR_GENOME_BUILD_MIX = 'ERROR_GENOME_BUILD_MIX';
export const ERROR_GENOME_BUILD_NOT_DETECTED =
  'ERROR_GENOME_BUILD_NOT_DETECTED';
export const ERROR_GENOME_BUILD_NOT_ENOUGH = 'ERROR_GENOME_BUILD_NOT_ENOUGH';
export const ERROR_HET_RATIO = 'ERROR_HET_RATIO';
